### ISSUE TITLE
Unable to select RECEIVED_DATA option from the side bar of infiniteScroll machine.

### ISSUE THREAD

**Issue by sdserage** [mattpocock/xstate-catalogue#11]
<img width="1680" alt="Screen Shot 2021-04-06 at 1 31 03 PM" src="https://user-images.githubusercontent.com/31323515/113746406-acbd7100-96dc-11eb-90f4-58eab285d0fd.png">

The focused button doesn’t interact with mouse click or keyboard. Other uses of 'RECEIVED_DATA' work on the page as expected.

**Comment by sdserage** [comment]
Update: Tested this on Chrome, Safari and Firefox on macOS Big Sur.

**Comment by mattpocock** [comment]
Thanks for the bug report!

**Comment by bemayr** [comment]
Wow, that was fast! 😂👏
