### ISSUE TITLE
xstate-catalogue CatalogueSearcher modal keyboard shortcut `ctrl + k` conflicts with chrome and firefox keyboard default shortcuts

### ISSUE THREAD

**Issue by AdamMescher** [mattpocock/xstate-catalogue#17]
While using a Windows 10 machine [version 19042.906], user attempts to open the "search machines" modal with the `ctrl + k` chord trigger the `Focus Address bar for Web Search (writes "? " there)` search shortcut in Firefox (Version 87.0 (64-bit))[1] and the `Search from anywhere on the page` address bar shortcut in Chrome (version 89.0.4389.114) [2]

macOS users do not appear to have a similar conflict.

[1] - https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
[2] - https://support.google.com/chrome/answer/157179?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Caddress-bar-shortcuts

| Screen Recording |
| --- |
| https://user-images.githubusercontent.com/6540117/113804474-d5b12680-971b-11eb-92da-a23b0cfd9764.mp4 |

| Chrome Result | Firefox Result |
| --- | --- |
| ![chrome](https://user-images.githubusercontent.com/6540117/113803514-f24c5f00-9719-11eb-93a8-766f836af901.png) | ![firefox](https://user-images.githubusercontent.com/6540117/113803482-e365ac80-9719-11eb-8d74-c7ec307064b1.png) |

| Chrome Shortcuts | Firefox Shortcuts |
| --- | --- |
| ![chrome-shortcuts](https://user-images.githubusercontent.com/6540117/113803543-fc6e5d80-9719-11eb-8976-3dd6ba63974c.png) | ![firefox-keyboard-shortcuts](https://user-images.githubusercontent.com/6540117/113803566-06905c00-971a-11eb-8ef9-d00f9402ade5.png) |

**Comment by AdamMescher** [comment]
User experience could benefit from update to default keyboard shortcut to open the search modal to something that does not conflict with default browser configuration or disabling of default behavior in Chrome and Firefox.

**Comment by mattpocock** [comment]
What do TailwindCSS use on Windows? as their hotkey?

**Comment by bemayr** [comment]
> What do TailwindCSS use on Windows as their hotkey?

Ok, that's interesting 🤔, they use `Ctrl + K` but it does not trigger the browser's search behavior...
Let's see how they are doing that.

**Comment by bemayr** [comment]
Ok, i found the piece of code accomplishing this in TailwindCSS, they are using @docsearch/react via algolia and there it is implemented via a simple [`event.preventDefault()`](https://github.com/francoischalifour/autocomplete.js/blob/5697895167e7bdc61429b9794c92ef57cd0315bc/packages/docsearch-react/src/useDocSearchKeyboardEvents.ts#L10)

🠖 PR incoming 👌

**Comment by mattpocock** [comment]
OK cool - I'm happy to close based on that
