### ISSUE TITLE
Broken in Safari

### ISSUE THREAD

**Issue by PetrSnobelt** [mattpocock/xstate-catalogue#33]
When you use the trackpad for scrolling, arrows are disconnected ...

<img width="611" alt="Xstate-visualizer" src="https://user-images.githubusercontent.com/1737335/114216520-4c8e2f80-9967-11eb-886a-8ccecc9cab4d.png">

Great project, thank you!

**Comment by mattpocock** [comment]
@PetrSnobelt This is a duplicate of #4, which is closed because it's a bug with `@xstate/inspect`

**Comment by mattpocock** [comment]
Also, thanks! :)
