### ISSUE TITLE
Button not working on infinite scroll

### ISSUE THREAD

**Issue by arturcarvalho** [mattpocock/xstate-catalogue#45]
Hi there,

@mattpocock as we spoke yesterday on twitter, I can't click on the received_data. I can only trigger the error. 

I've tried on chrome on a windows and mac os machine. 
![image](https://user-images.githubusercontent.com/2487710/116972969-191b9800-acbc-11eb-9e8b-531fb6094f16.png)

And thank you very much for this project! :)

**Comment by mattpocock** [comment]
Gotcha! Yes, this is actually a bug with @xstate/inspect - you can't specify event payloads when you pass your machine across. I'll leave this issue open because someone may have a creative solution.

The way to get the interaction you're looking for is to click in the interactive descriptions, not in the inspector - only some of the events work in the inspector.

**Comment by arturcarvalho** [comment]
Oh, didn't know the states under were clickable. Nice touch!

I see what you mean. I've made it work by removing the `...event.data` from the `assignDataContext`.  
https://xstate.js.org/viz/?gist=417f16e87b4ce6e7e83d729eefdf06dd

If I may suggest:
- You could put the states on a row higher in the page instead of on the side. I can't see the transition happening because when I scroll to the state, the diagram disappears.
- Probably had a drop shadow or something else that makes the states look more clickable.

In any case this is already working well enough. Zooming to 90% makes the event `RECEIVED_DATA` visible.

Thank you very much for the reply!

**Comment by mattpocock** [comment]
You can also change the layout of the page to show the diagram on the left/50/50 vertical by clicking the toggle in the top right. Does that help?

**Comment by arturcarvalho** [comment]
Oh yeah... I thought the icon was a menu. This is much better no doubt, thank you!

**Comment by mattpocock** [comment]
Closing this
