### ISSUE TITLE
Copy button on mobile hides content

### ISSUE THREAD

**Issue by dylanklohr** [mattpocock/xstate-catalogue#5]
## Description

When viewing any machine src on mobile, the `Copy to Clipboard` button covers content in the code block, making it difficult to see the first few lines of the machine src. 

![image](https://user-images.githubusercontent.com/17390173/113705512-20db2300-96a3-11eb-9398-b180a8268b7a.jpeg)

**Comment by mattpocock** [comment]
Padding width is probably too wide on that <pre> tag as well!

**Comment by bemayr** [comment]
Sorry I didn't comment here before opening the PR, I was too concerned finally diving a little bit into Tailwind. If you like the idea I am happy and otherwise I can/will just adapt it. 😉

**Comment by mattpocock** [comment]
@bemayr Commented on the PR - thanks for the code!
