### ISSUE TITLE
typescript show error message with "authentication.machine.ts"

### ISSUE THREAD

**Issue by Sunqinying** [mattpocock/xstate-catalogue#54]
In my vscode,  the section "authentication.machine.ts" show an error with 
```
(property) clearUserDetailsFromContext: AssignAction<{
    userDetails: undefined;
}, EventObject>
Type 'AssignAction<{ userDetails: undefined; }, AuthenticationMachineEvent>' is not assignable to type 'ActionObject<AuthenticationMachineContext, AuthenticationMachineEvent> | ActionFunction<AuthenticationMachineContext, AuthenticationMachineEvent>'.
  Type 'AssignAction<{ userDetails: undefined; }, AuthenticationMachineEvent>' is not assignable to type 'ActionObject<AuthenticationMachineContext, AuthenticationMachineEvent>'.
```

my ts config as below:
```json
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "build"
  },
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ]
}

```

ts version:
```
    "typescript": "^4.0.3"
```

**Comment by mattpocock** [comment]
@Sunqinying What xstate version are you running?

**Comment by Sunqinying** [comment]
> @Sunqinying What xstate version are you running?

4.19.1

**Comment by mattpocock** [comment]
Try this:

```ts
clearUserDetailsFromContext: assign((context) => {
  return { userDetails: undefined }
})

```

**Comment by Sunqinying** [comment]
> Try this:
> 
> ```ts
> clearUserDetailsFromContext: assign((context) => {
>   return { userDetails: undefined }
> })
> ```

It's ok now

Is this caused because 
``` typescript
export interface ActionObject<TContext, TEvent extends EventObject> {
    /**
     * The type of action that is executed.
     */
    type: string;
    /**
     * The implementation for executing the action.
     */
    exec?: ActionFunction<TContext, TEvent>;
    [other: string]: any;
}
```
not compatibel with 
``` typescript
export interface AssignAction<TContext, TEvent extends EventObject> extends ActionObject<TContext, TEvent> {
    type: ActionTypes.Assign;
    assignment: Assigner<TContext, TEvent> | PropertyAssigner<TContext, TEvent>;
}
```

**Comment by Sunqinying** [comment]
> > Try this:
> > ```ts
> > clearUserDetailsFromContext: assign((context) => {
> >   return { userDetails: undefined }
> > })
> > ```
> 
> It's ok now
> 
> Is this caused because
> 
> ```ts
> export interface ActionObject<TContext, TEvent extends EventObject> {
>     /**
>      * The type of action that is executed.
>      */
>     type: string;
>     /**
>      * The implementation for executing the action.
>      */
>     exec?: ActionFunction<TContext, TEvent>;
>     [other: string]: any;
> }
> ```
> 
> not compatibel with
> 
> ```ts
> export interface AssignAction<TContext, TEvent extends EventObject> extends ActionObject<TContext, TEvent> {
>     type: ActionTypes.Assign;
>     assignment: Assigner<TContext, TEvent> | PropertyAssigner<TContext, TEvent>;
> }
> ```

**Comment by Sunqinying** [comment]
> > Try this:
> > ```ts
> > clearUserDetailsFromContext: assign((context) => {
> >   return { userDetails: undefined }
> > })
> > ```
> 
> It's ok now
> 
> Is this caused because
> 
> ```ts
> export interface ActionObject<TContext, TEvent extends EventObject> {
>     /**
>      * The type of action that is executed.
>      */
>     type: string;
>     /**
>      * The implementation for executing the action.
>      */
>     exec?: ActionFunction<TContext, TEvent>;
>     [other: string]: any;
> }
> ```
> 
> not compatibel with
> 
> ```ts
> export interface AssignAction<TContext, TEvent extends EventObject> extends ActionObject<TContext, TEvent> {
>     type: ActionTypes.Assign;
>     assignment: Assigner<TContext, TEvent> | PropertyAssigner<TContext, TEvent>;
> }
> ```
> 
> and there should no difference whether passed a function or object, because the declaration for assign return the same type
> 
> ```ts
> export declare const assign: <TContext, TEvent extends EventObject = EventObject>(assignment: Assigner<TContext, TEvent> | PropertyAssigner<TContext, TEvent>) => AssignAction<TContext, TEvent>;
> ```

xstate say the same proble

> However, TypeScript inference isn't perfect, so the responsible thing to do is to add the context and event as generics into assign<Context, Event>(...):
``` typescript
// ...
on: {
  INCREMENT: {
    // Generics guarantee proper inference
    actions: assign<CounterContext, CounterEvent>({
      count: (context) => {
        // context: { count: number }
        return context.count + 1;
      }
    });
  }
}
// ...
```
