### ISSUE TITLE
UX: navigation with mouse wheel

### ISSUE THREAD

**Issue by FedericoBiccheddu** [mattpocock/xstate-catalogue#57]
Navigating the examples using the mouse wheel as a scroll method, when I start to scroll with the mouse hover the inspector with the default layout (hamburger with 4 lines), the visualization moves out; especially while scrolling up.

![image](https://user-images.githubusercontent.com/433819/124574686-01db6100-de4b-11eb-8f5f-e34e0f73f249.png)

I did try to solve the problem, but without success.

I'm using Firefox 89.0.2 (64-bit).

**Comment by mattpocock** [comment]
Duplicate of #7, closing
