### ISSUE TITLE
Scroll in the visualizer 

### ISSUE THREAD

**Issue by ivorpad** [mattpocock/xstate-catalogue#7]
Unfortunately we're unable to scroll in this section

<img width="513" alt="Screenshot 2021-04-06 at 15 28 38" src="https://user-images.githubusercontent.com/52452/113718332-d1b9e000-96ec-11eb-9e3e-c7539573bfd0.png">

**Comment by mattpocock** [comment]
@ivorpad Which browser are you using? And which layout (top right button) are you using?

**Comment by ivorpad** [comment]
Firefox (lts) + both layouts.

**Comment by hmaurer** [comment]
The issue is not browser specific. Here's on Chrome:
https://www.loom.com/share/69994a0b5b7c4137b804532b0cd38abc

It's just an `overflow-y: auto` missing I think. Here's with the overflow added:
https://www.loom.com/share/0ed0e51a37ad4c1ea65a2b3c17c11307

**Comment by mattpocock** [comment]
@hmaurer Can you PR this so we get a preview link from Vercel?

**Comment by hmaurer** [comment]
@mattpocock erm well I think this would be a change to the xstate visualiser? (https://statecharts.io/inspect) (I just added `overflow-y: auto` in the devtools!).

**Comment by mattpocock** [comment]
Haha oh I see... Hmmm. Paging @davidkpiano

**Comment by jamesking** [comment]
This might be a related issue? In Safari when scrolling in the Xstate Visualiser, there is an odd behaviour where the transitions get detached from the states: 

![Screen Recording 2021-04-07 at 13 29 15](https://user-images.githubusercontent.com/11338/113875608-da72ea80-97ae-11eb-95be-cf6f84d8378b.gif)

Awesome work @mattpocock. Thank you!

**Comment by mattpocock** [comment]
@jamesking #4 This has been reported there

Thanks!

**Comment by jamesking** [comment]
Thanks @mattpocock! Sorry - I didn't think to check the closed issues.  👍

**Comment by ivorpad** [comment]
Since this is not an issue in the catalogue I think it's safe to close it.

**Comment by mattpocock** [comment]
Reopened in error
